### ISSUE TITLE
thank you + license?

### ISSUE THREAD

**Issue by berteh** [akquinet/ResponsiveLime#1]
thanks for the nice template.
what are your terms to allow re-uses of it?

**Comment by grundm** [comment]
Hi Berteh,

Thank you. We did not assign a specific license yet, but the template is free of charge and can be edited. Maybe you are even interested in contributing, since there are still a few open points as indicated in README.md

Best, Martin

**Comment by grundm** [comment]
Hi Berteh,

We added the GNU General Public License v3, since LimeSurvey is licensed under GPL v3.

Best, Martin
