### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by nickanti** [akquinet/ResponsiveLime#3]
Unable to find startpage.pstpl to add {TEMPLATEJS} placeholder, please check your template.

**Comment by grundm** [comment]
Hi Nick,

In the past, I met this error message as well. There might be two possible reasons that we can rule out hopefully.

### ZIP-file

Are you using a Mac?
Did you select all files within the ResponsiveLime directory to zip them?

### PHP Module

Did you install LimeSurvey?

**Comment by nickanti** [comment]
I have a mac, but I did not zip on a mac - I used the Download Zip button on this page:
https://github.com/akquinet/ResponsiveLime

Yes I have LimeSurvey (2.0.5) installed

**Comment by grundm** [comment]
Could you please unzip the downloaded directory and then call the following commands within the directory in the Terminal app:

```
zip -r ResponsiveLime.zip . -x *.git* -x *.DS_Store* uncompressed
mv ResponsiveLime.zip ..
```

**Comment by nickanti** [comment]
Yup - that was it - guess you can close/reject this item or maybe also setup a download area with properly formatted zip file. Although I think that the lime installer should be smart enough to ignore these extra invisible files.
